server:
  port: 8080

application:
  security:
    jwt:
      secret-key: mi_super_clave_secreta_que_nadie_ni_469234556_*879/5656895-487_persoñas_saben
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # a week

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
